/*
 * This source file was generated by the Gradle 'init' task
 */
package demo;

import demo.SchemaRegistry.CompatibilityType;
import demo.FieldValue.FieldType;
import demo.Schema.SchemaBuilder;

public class App {
    public static void main(String[] args) {

        SchemaRegistry schemaRegistry = new SchemaRegistry(CompatibilityType.BACKWARD);

        try {
            schemaRegistry.putSchema(SchemasUtil.avro1);
            schemaRegistry.putSchema(SchemasUtil.avro6);
        } catch (SchemaEvolutionException exception) {
            System.out.println(exception);
        }
    }
}
